// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BlazorApp.Migrations
{
    [DbContext(typeof(GameDbContext))]
    [Migration("20211123043228_Initial-Commit")]
    partial class InitialCommit
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("Game", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Console")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageLink")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<float>("OriginalPrice")
                        .HasColumnType("REAL");

                    b.Property<float>("Price")
                        .HasColumnType("REAL");

                    b.HasKey("ID");

                    b.ToTable("Game");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Console = 0,
                            Description = "Grand Theft Auto V is an action-adventure game played from either a third-person or first-person perspective. Players complete missions—linear scenarios with set objectives—to progress through the story. Outside of the missions, players may freely roam the open world.",
                            ImageLink = "Images/GTAV.jpg",
                            Name = "Grand Theft Auto V",
                            OriginalPrice = 34.99f,
                            Price = 29.99f
                        },
                        new
                        {
                            ID = 2,
                            Console = 5,
                            Description = "In the game, Mario must race through the Mushroom Kingdom and save Princess Toadstool (later Princess Peach) from Bowser. Mario jumps, runs, and walks across each level. The worlds are full of enemies and platforms, and open holes.",
                            ImageLink = "Images/SuperMario.png",
                            Name = "Mario Pratt",
                            OriginalPrice = 24.99f,
                            Price = 19.99f
                        },
                        new
                        {
                            ID = 3,
                            Console = 0,
                            Description = "The Elder Scrolls V: Skyrim is an action role-playing game, playable from either a first or third-person perspective. The player may freely roam over the land of Skyrim—an open world environment consisting of wilderness expanses, dungeons, caves, cities, towns, fortresses, and villages.",
                            ImageLink = "Images/skyrim.png",
                            Name = "Skyrim 90th edition",
                            OriginalPrice = 34.99f,
                            Price = 14.99f
                        },
                        new
                        {
                            ID = 4,
                            Console = 3,
                            Description = "The game simulates the infantry and combined arms warfare of World War II",
                            ImageLink = "Images/COD.jpg",
                            Name = "Call of Duty",
                            OriginalPrice = 31.49f,
                            Price = 17.99f
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
