// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BlazorApp.Migrations.ReviewDb
{
    [DbContext(typeof(ReviewDbContext))]
    partial class ReviewDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("Review", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<int>("GameID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ReviewDescription")
                        .HasColumnType("TEXT");

                    b.Property<int>("Stars")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Username")
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("Review");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Date = new DateTime(2019, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GameID = 1,
                            ReviewDescription = "This game sucks",
                            Stars = 1,
                            Username = "GameCritic1"
                        },
                        new
                        {
                            ID = 2,
                            Date = new DateTime(2019, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GameID = 1,
                            ReviewDescription = "This game is ok",
                            Stars = 2,
                            Username = "GameCritic2"
                        },
                        new
                        {
                            ID = 3,
                            Date = new DateTime(2019, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GameID = 1,
                            ReviewDescription = "This game is decent",
                            Stars = 3,
                            Username = "GameCritic3"
                        },
                        new
                        {
                            ID = 4,
                            Date = new DateTime(2018, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GameID = 1,
                            ReviewDescription = "This game is average",
                            Stars = 4,
                            Username = "GameCritic4"
                        },
                        new
                        {
                            ID = 5,
                            Date = new DateTime(2013, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GameID = 1,
                            ReviewDescription = "This game is great",
                            Stars = 5,
                            Username = "GameCritic5"
                        },
                        new
                        {
                            ID = 6,
                            Date = new DateTime(2019, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GameID = 2,
                            ReviewDescription = "This game sucks",
                            Stars = 1,
                            Username = "GameCritic1"
                        },
                        new
                        {
                            ID = 7,
                            Date = new DateTime(2019, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GameID = 2,
                            ReviewDescription = "This game is ok",
                            Stars = 2,
                            Username = "GameCritic2"
                        },
                        new
                        {
                            ID = 8,
                            Date = new DateTime(2019, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GameID = 2,
                            ReviewDescription = "This game is decent",
                            Stars = 3,
                            Username = "GameCritic3"
                        },
                        new
                        {
                            ID = 9,
                            Date = new DateTime(2018, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GameID = 2,
                            ReviewDescription = "This game is Terrible",
                            Stars = 1,
                            Username = "GameCritic4"
                        },
                        new
                        {
                            ID = 10,
                            Date = new DateTime(2013, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GameID = 2,
                            ReviewDescription = "This game is great",
                            Stars = 5,
                            Username = "GameCritic5"
                        },
                        new
                        {
                            ID = 11,
                            Date = new DateTime(2019, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GameID = 1,
                            ReviewDescription = "This game sucks",
                            Stars = 1,
                            Username = "GameCritic1"
                        },
                        new
                        {
                            ID = 12,
                            Date = new DateTime(2011, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GameID = 3,
                            ReviewDescription = "This game is ok",
                            Stars = 2,
                            Username = "GameCritic2"
                        },
                        new
                        {
                            ID = 13,
                            Date = new DateTime(2014, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GameID = 3,
                            ReviewDescription = "This game is decent",
                            Stars = 3,
                            Username = "GameCritic3"
                        },
                        new
                        {
                            ID = 14,
                            Date = new DateTime(2021, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GameID = 3,
                            ReviewDescription = "This game is average",
                            Stars = 4,
                            Username = "GameCritic4"
                        },
                        new
                        {
                            ID = 15,
                            Date = new DateTime(2015, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GameID = 3,
                            ReviewDescription = "This game is great",
                            Stars = 5,
                            Username = "GameCritic5"
                        },
                        new
                        {
                            ID = 16,
                            Date = new DateTime(2012, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GameID = 4,
                            ReviewDescription = "This game sucks",
                            Stars = 1,
                            Username = "GameCritic1"
                        },
                        new
                        {
                            ID = 17,
                            Date = new DateTime(2011, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GameID = 4,
                            ReviewDescription = "This game is ok",
                            Stars = 2,
                            Username = "GameCritic2"
                        },
                        new
                        {
                            ID = 18,
                            Date = new DateTime(2016, 8, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GameID = 4,
                            ReviewDescription = "This game is decent",
                            Stars = 5,
                            Username = "GameCritic3"
                        },
                        new
                        {
                            ID = 19,
                            Date = new DateTime(2020, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GameID = 4,
                            ReviewDescription = "This game is not fun at all to play",
                            Stars = 3,
                            Username = "GameCritic4"
                        },
                        new
                        {
                            ID = 20,
                            Date = new DateTime(2008, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GameID = 4,
                            ReviewDescription = "This game is great",
                            Stars = 5,
                            Username = "GameCritic5"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
