// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BlazorApp.Migrations.UserDb
{
    [DbContext(typeof(UserDbContext))]
    partial class UserDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("User", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("User");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Email = "lassorocks@gmail.com",
                            FirstName = "Bob",
                            LastName = "Lasso",
                            Password = "Password"
                        },
                        new
                        {
                            ID = 2,
                            Email = "sarahforprez@outlook.com",
                            FirstName = "Sarah",
                            LastName = "Chapman",
                            Password = "$chap4potus"
                        },
                        new
                        {
                            ID = 3,
                            Email = "late4class@hotmail.com",
                            FirstName = "Kevin",
                            LastName = "Roger",
                            Password = "incorrect"
                        },
                        new
                        {
                            ID = 4,
                            Email = "etsuadmin@etsu.edu",
                            FirstName = "ETSUadmin",
                            LastName = "ETSUadmin",
                            Password = "root"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
